### ISSUE TITLE
Unify NodeJS dependency declarations into Bazel

### ISSUE THREAD

**Issue by lolski** [vaticle/typedb-client-nodejs#172]
Right now, some dependencies and their respective version numbers are declared in `package.json`. This is not ideal and they should be declared in Bazel instead.

**Comment by haikalpribadi** [comment]
Is this even possible? 🤔

**Comment by haikalpribadi** [comment]
@vmax ?

**Comment by lolski** [comment]
> Is this even possible?

we'll first need to do the research on whether it is possible. @haikalpribadi

**Comment by alexjpwalker** [comment]
@lolski This is technically possible, but not recommended. (Almost) all JavaScript and TypeScript projects use the `package.json` format for declaring dependencies. There are alternatives - a couple of Medium articles discuss this, including https://blog.bitsrc.io/4-npm-alternatives-best-js-package-managers-and-publishing-tools-fe6779937ee9 - but they are not well-known and it would not be beneficial for us to use a package manager with very low adoption in a secondary language in our ecosystem.

We will surely continue to use Bazel, and so it makes sense for us to use the Bazel `npm` rules that we already use: 
```py
# Load package.json
node_repositories(
    package_json = ["//:package.json"]
)
yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)
```
Note that this then allows our `yarn`-installed packages to be referenced as Bazel targets, akin to our usage of Maven inside Bazel: 
```py
ts_project(
    name = "client-nodejs",
    srcs = glob([
        "*.ts",
        "api/**/*.ts",
        "common/**/*.ts",
        "connection/**/*.ts",
        "concept/**/*.ts",
        "logic/**/*.ts",
        "query/**/*.ts",
        "stream/**/*.ts",
    ]),
    tsconfig = "tsconfig.json",
    declaration = True,
    deps = [
        "@npm//@grpc/grpc-js",
        "@npm//@types/node",
        "@npm//@types/uuid",
        "@npm//typedb-protocol",
        "@npm//typescript",
        "@npm//uuid",
    ],
)
```
I will close this issue - feel free to reopen if there is anything I'm missing that would cause our current behaviour to be incorrect.
